name: Build and Release Tauri App for Windows

on:
  push:
    branches:
      - beta

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      run: pnpm install

    - name: Build Tauri app for Windows
      run: pnpm tauri build

    - name: Create Release
      uses : ncipollo/release-action@v1
      with:
        artifacts: '.\\src-tauri\\target\\release\\**\\*.exe, .\\src-tauri\\target\\release\\**\\*.msi'
        token: ${{ secrets.GITHUB_TOKEN }}
        name: 'Beta Release'
        tag: 'beta'